# Generated by Django 3.2.5 on 2021-08-05 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='device',
            new_name='cookie',
        ),
    ]
